# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('xuehao', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('jianjie', models.TextField()),
            ],
        ),
    ]
