# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_classify_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='add_adminuser_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_manage.Manage'),
        ),
    ]
