# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-17 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Parentid', models.IntegerField()),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.IntegerField()),
                ('add_time', models.CharField(max_length=30)),
                ('add_adminuser_id', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('classify_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Classify')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('status', models.SmallIntegerField()),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.CharField(max_length=30)),
                ('sort', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('add_username', models.CharField(max_length=30)),
                ('add_time', models.CharField(max_length=30)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Home_floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home_floor_commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity')),
                ('floot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Home_floor')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('add_user', models.CharField(max_length=30)),
                ('add_time', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.CharField(max_length=32, unique=True)),
                ('add_time', models.CharField(max_length=30)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_time', models.CharField(max_length=30)),
                ('pay_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_type', models.CharField(max_length=50)),
                ('pay_status', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_particulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order_form')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.IntegerField()),
                ('checked', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Receiving_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.CharField(max_length=32)),
                ('Address', models.CharField(max_length=300)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User')),
            ],
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='order_form',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='commodity_evaluate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='commodity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Commodity'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
    ]
