# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180920_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
