# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-06 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180928_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_receiving_address',
            name='status',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
