# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20181006_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_form',
            name='pay_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
