# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-20 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180917_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classify',
            name='Address',
        ),
    ]
