# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180920_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity_img',
            old_name='content',
            new_name='path',
        ),
        migrations.AddField(
            model_name='commodity_img',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
