# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180924_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_floor',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='home_floor',
            name='add_user',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
