# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_res', '0003_remove_user_aaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
