# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-13 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_res', '0004_auto_20180913_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jianjie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
