# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manage', '0003_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='parent_id',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
