# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manage', '0002_auto_20180919_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField(default=0)),
                ('control', models.CharField(max_length=50, null=True)),
                ('fun', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
