# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manage', '0004_auto_20180925_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='role_power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_manage.Power')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_manage.Role')),
            ],
        ),
    ]
