# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manage', '0006_manage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='urlname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
