# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-14 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
                ('sex', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=6)),
                ('zhuanye', models.CharField(max_length=50)),
                ('clas', models.CharField(max_length=50)),
            ],
        ),
    ]
