# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-14 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='neme',
            new_name='name',
        ),
    ]
