# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-14 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manage', '0002_auto_20180914_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pswd', models.CharField(max_length=50)),
            ],
        ),
    ]
