# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aaa',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
